#!/bin/sh
BASE_NAME="${1:-dev}"
SESSION_NAME="${BASE_NAME}-0"
COUNTER=1

while tmux has-session -t "$SESSION_NAME" 2>/dev/null; do
    SESSION_NAME="${BASE_NAME}-${COUNTER}"
    COUNTER=$((COUNTER + 1))
done

tmux new-session -d -s "$SESSION_NAME" -x - -y -
# Two columns: left 24%, right 76%
tmux split-window -t "$SESSION_NAME" -h -l 76%
# Focus the right pane
tmux select-pane -t "$SESSION_NAME:0.1"
tmux -2 attach-session -t "$SESSION_NAME" -d
